### ISSUE TITLE
Fails to run portably

### ISSUE THREAD

**Issue by hiddeninthesand** [srevinsaju/element-appimage#5]
While attempting to run the appimage portably (by using a home and config directory in the same root directory as the appimage) it fails to launch, spitting out `Invalid configuration: no default server specified.`

**Comment by andreas-tritum** [comment]
You need to put a config.json file int your profile-folder.
Element needs two sub-folders in the `appimage.config` folder: `Riot` and `Element`.
You need the to put a `config.json` in the `Element`-folder, which is the profile folder. ("Element" is the default profile name )
You can download https://raw.githubusercontent.com/vector-im/element-web/develop/config.sample.json and rename it to `config.json` The file needs no further modifcation.

**Comment by MurdoMaclachlan** [comment]
Doesn't fix for me.

Console output in [this gist](https://gist.github.com/MurdoMaclachlan/2c92fa26aa15b9016e63bdcca5e6412e).

**Comment by srevinsaju** [comment]
Fixed in https://github.com/srevinsaju/element-appimage/commit/83b0d2f2659b3e649ff66d75372cd8dc3e4f0274, let me know if the issue persists.
